# Generated by Django 3.2.9 on 2021-11-07 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('profile', models.ImageField(upload_to='profile', verbose_name='profile pic')),
                ('phone', models.CharField(max_length=14, null=True, verbose_name='phone number')),
                ('specialist', models.CharField(blank=True, max_length=500, verbose_name='subject specialist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(max_length=500, upload_to='files')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
