# Generated by Django 3.2.9 on 2021-11-07 06:12

from django.db import migrations
import shareApp.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shareApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', shareApp.manager.NewBaseManager()),
            ],
        ),
    ]
