# Generated by Django 3.2.9 on 2021-11-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareApp', '0003_auto_20211107_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
