# Generated by Django 3.2.9 on 2021-11-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareApp', '0004_alter_filemodel_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
