# Generated by Django 3.2.9 on 2021-11-10 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareApp', '0006_auto_20211110_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='uploaded_at',
            field=models.DateField(default=datetime.datetime(2021, 11, 10, 11, 50, 25, 774740)),
        ),
    ]
