# Generated by Django 3.2.9 on 2021-11-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareApp', '0008_alter_filemodel_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='qrcode',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
