# Generated by Django 3.2.9 on 2021-11-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareApp', '0009_filemodel_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='f',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='files'),
        ),
    ]
