# Generated by Django 3.2.9 on 2021-11-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareApp', '0010_filemodel_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='f',
        ),
    ]
