# Generated by Django 3.2.9 on 2021-11-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareApp', '0011_remove_filemodel_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='downloadurl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
